apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

resources:
  - ../base
  - 20-httproute.yaml

images:
  - name: harbor.nplan.local:80/neuroplan/frontend
    newTag: "98e5dc3"

  - name: harbor.nplan.local:80/neuroplan/backend
    newTag: "7720ba1"
